- name: catalogue
  hosts: catalogue
  become: yes
  tasks: 
  - name: disable and enable nodejs
  ansible.builtin.command: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  
  - name: Install nodejs
    ansible.builtin.dnf:
      name: nodejs
      state: present

  - name: add user roboshop
  ansible.builtin.user:
    name: roboshop

  - name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory

      