- name: web
  hosts: web
  become: yes
  tasks:
  - name: install nginx service
    ansible.builtin.dnf:
      name: nginx
      state: present

  - name: remove html durectory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Download web application
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/web.zip
      dest: /tmp

  - name: Extract web application
    ansible.builtin.unarchive:
      src: /tmp/web.zip
      dest: /usr/share/nginx/html
      remote_src: yes

  - name: copy roboshop configuration
    ansible.builtin.copy:
      src: roboshop.conf
      dest: /etc/nginx/default.d/roboshop.conf

  - name: start and enable web
    ansible.builtin.service:
      name: web
      state: started
      enabled: yes


  

  

  
